import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MCP_CONFIG_TARGETS, SKILL_TARGETS } from '../src/hosts.js';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// The repo's per-host copies are generated by `npm run sync:agents` from the
// canonical sources. These pin that they were actually regenerated after the
// last canonical edit, and that the committed MCP config stayed machine-independent
// (the runtime writer in src/hosts.js produces absolute paths for USER projects
// and must never be what lands here).

test('every committed skill copy is byte-identical to skills/ripple/SKILL.md', () => {
  const canonical = readFileSync(join(repoRoot, 'skills/ripple/SKILL.md'));
  for (const relPath of SKILL_TARGETS) {
    assert.ok(
      readFileSync(join(repoRoot, relPath)).equals(canonical),
      `${relPath} is out of sync — run "npm run sync:agents"`
    );
  }
});

test('every committed MCP config copy is byte-identical to mcp/mcp-config.json', () => {
  const canonical = readFileSync(join(repoRoot, 'mcp/mcp-config.json'));
  for (const { path: relPath } of MCP_CONFIG_TARGETS) {
    assert.ok(
      readFileSync(join(repoRoot, relPath)).equals(canonical),
      `${relPath} is out of sync — run "npm run sync:agents"`
    );
  }
});

test('the committed MCP config carries no machine-specific path or RIPPLE_PROJECT_ROOT', () => {
  const raw = readFileSync(join(repoRoot, 'mcp/mcp-config.json'), 'utf8');
  const entry = JSON.parse(raw).mcpServers.ripple;
  assert.ok(!raw.includes('RIPPLE_PROJECT_ROOT'), 'committed config must rely on host cwd, not a pinned root');
  for (const arg of entry.args) {
    assert.ok(!isAbsolute(arg), `committed config arg must be relative, got ${arg}`);
  }
});

// mcp/src resolves its imports from the package root's node_modules on a normal
// install (root dependencies are authoritative); mcp/package.json exists for
// running the server standalone and must not drift from what the root ships.
test('mcp/package.json dependency ranges mirror the root package.json', () => {
  const root = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8')).dependencies;
  const nested = JSON.parse(readFileSync(join(repoRoot, 'mcp/package.json'), 'utf8')).dependencies;
  for (const [name, range] of Object.entries(nested)) {
    assert.equal(root[name], range, `${name}: root has ${root[name]}, mcp/package.json has ${range}`);
  }
});
